---
namespace: mschuchard
name: general
version: 1.0.0
readme: README.md
authors:
- Matthew Schuchard <example@domain.com>
description: General collection of Ansible plugins for common tools associated with "DevOps"
license_file: LICENSE
tags:
- packer
- goss
dependencies: {}
repository: https://github.com/mschuchard/ansible.general
documentation: http://docs.example.com
homepage: https://galaxy.ansible.com/mschuchard/general
issues: https://github.com/mschuchard/ansible.general/issues
build_ignore: []
