---
namespace: mschuchard
name: general
version: 1.3.0
readme: README.md
authors:
- Matthew Schuchard <example@domain.com>
description: General collection of Ansible module plugins for common tools associated with "DevOps"
license_file: LICENSE
tags:
- faas
- goss
- packer
- puppet
- terraform
dependencies: {}
repository: https://github.com/mschuchard/ansible.general
documentation: https://galaxy.ansible.com/ui/repo/published/mschuchard/general/docs
homepage: https://github.com/mschuchard/ansible.general
issues: https://github.com/mschuchard/ansible.general/issues
build_ignore:
- .git
- .circleci
- .github
- '__pycache__'
- .ruff_cache
- .pytest_cache
- .gitignore
- galaxy.yml
- pyproject.toml
- ruff.toml
- '*.tar.gz'
- CHANGELOG.md
