---
version: 2.1

jobs:
  test:
    environment:
      PYTHONPATH: /tmp/project
    working_directory: /tmp/project/mschuchard/general
    docker:
    - image: matthewschuchard/ansible-module
    resource_class: small
    steps:
    - checkout
    - run:
        name: ruff
        command: ruff check .
    - run:
        name: pytest module utils
        command: pytest tests/unit/plugins/module_utils

workflows:
  execute_tests:
    jobs:
    - test
