---
version: 2.1

jobs:
  test:
    environment:
      PYTHONPATH: /tmp/project
    working_directory: /tmp/project/mschuchard/general
    docker:
    - image: matthewschuchard/ansible-module
    resource_class: small
    steps:
    - checkout
    - run:
        name: pylint
        command: pylint --recursive=y . || true
    - run:
        name: flake8
        command: flake8 .
    - run:
        name: ruff
        command: ruff check .

workflows:
  execute_tests:
    jobs:
    - test
