---
version: 2.1

jobs:
  test:
    environment:
      PYTHONPATH: /tmp/project
    working_directory: /tmp/project/mschuchard/general
    docker:
    - image: matthewschuchard/ansible-module
    resource_class: small
    steps:
    - checkout
    - restore_cache:
        keys:
        - mschuchard-ansible-general
    - run:
        name: pylint
        command: pylint --recursive=y . || true
    - run:
        name: flake8
        command: flake8 .
    - save_cache:
        paths:
        - /usr/lib/python3/dist-packages
        key: mschuchard-ansible-general

workflows:
  execute_tests:
    jobs:
    - test
