---
name: test

on:
  push:
    branches: [master]
    paths:
    - '**.py'
  pull_request:
    branches: [master]
    paths:
    - '**.py'

jobs:
  go-build:
    env:
      PYTHONPATH: ${{ github.workspace }}
    runs-on: ubuntu-22.04
    container: matthewschuchard/ansible-module
    steps:
    - name: setup ansible collection namespace dir structure
      run: mkdir mschuchard
    - name: checkout
      uses: actions/checkout@v4
      with:
        path: mschuchard/general
    - name: ruff
      run: ruff check .
    - name: pytest info level
      run: pytest || true
